/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HR;

import javax.swing.UIManager;

/**
 *
 * @author Shanika
 */
public class MainInterface extends javax.swing.JFrame {

    /**
     * Creates new form MainInterface
     */
    public MainInterface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        parent = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        emp = new javax.swing.JPanel();
        esidepane = new javax.swing.JPanel();
        add = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        search = new javax.swing.JButton();
        reports = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        leave = new javax.swing.JPanel();
        lsidepane = new javax.swing.JPanel();
        addl = new javax.swing.JButton();
        apig = new javax.swing.JButton();
        viewl = new javax.swing.JButton();
        dell = new javax.swing.JButton();
        searchl = new javax.swing.JButton();
        reportl = new javax.swing.JButton();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        attendance = new javax.swing.JPanel();
        asidepane = new javax.swing.JPanel();
        addatt = new javax.swing.JButton();
        viewa = new javax.swing.JButton();
        reportl1 = new javax.swing.JButton();
        jDesktopPane3 = new javax.swing.JDesktopPane();
        discipline = new javax.swing.JPanel();
        dsidepane = new javax.swing.JPanel();
        addc = new javax.swing.JButton();
        viewc = new javax.swing.JButton();
        jDesktopPane4 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1370, 700));

        jTabbedPane1.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N

        add.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_Add_User_Male_26px.png"))); // NOI18N
        add.setText("Add employee");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        edit.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_Registration_26px.png"))); // NOI18N
        edit.setText("Edit employee");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });

        delete.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_Remove_User_Male_26px.png"))); // NOI18N
        delete.setText("Delete employee");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        search.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_Find_User_Male_26px_1.png"))); // NOI18N
        search.setText("Search employee");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        reports.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        reports.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_Combo_Chart_26px.png"))); // NOI18N
        reports.setText("Reports");

        javax.swing.GroupLayout esidepaneLayout = new javax.swing.GroupLayout(esidepane);
        esidepane.setLayout(esidepaneLayout);
        esidepaneLayout.setHorizontalGroup(
            esidepaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(esidepaneLayout.createSequentialGroup()
                .addGroup(esidepaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(search, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(edit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(add, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(reports, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        esidepaneLayout.setVerticalGroup(
            esidepaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(esidepaneLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(edit, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(reports, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1317, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 632, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout empLayout = new javax.swing.GroupLayout(emp);
        emp.setLayout(empLayout);
        empLayout.setHorizontalGroup(
            empLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(empLayout.createSequentialGroup()
                .addComponent(esidepane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        empLayout.setVerticalGroup(
            empLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(esidepane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, empLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Employee Management", emp);

        addl.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        addl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_Add_File_26px_1.png"))); // NOI18N
        addl.setText("Add leave");
        addl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addlActionPerformed(evt);
            }
        });

        apig.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        apig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_Check_File_26px.png"))); // NOI18N
        apig.setText("Approve/ Ignore");
        apig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apigActionPerformed(evt);
            }
        });

        viewl.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        viewl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_Today_26px.png"))); // NOI18N
        viewl.setText("View leaves");
        viewl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewlActionPerformed(evt);
            }
        });

        dell.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        dell.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_Delete_File_26px.png"))); // NOI18N
        dell.setText("Delete leave");
        dell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dellActionPerformed(evt);
            }
        });

        searchl.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        searchl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_View_26px.png"))); // NOI18N
        searchl.setText("Search leaves");
        searchl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchlActionPerformed(evt);
            }
        });

        reportl.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        reportl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_Combo_Chart_26px.png"))); // NOI18N
        reportl.setText("Reports");

        javax.swing.GroupLayout lsidepaneLayout = new javax.swing.GroupLayout(lsidepane);
        lsidepane.setLayout(lsidepaneLayout);
        lsidepaneLayout.setHorizontalGroup(
            lsidepaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lsidepaneLayout.createSequentialGroup()
                .addGroup(lsidepaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(reportl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dell, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(apig, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(searchl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        lsidepaneLayout.setVerticalGroup(
            lsidepaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lsidepaneLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(addl, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(apig, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(viewl, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(dell, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(searchl, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(reportl, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1341, Short.MAX_VALUE)
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout leaveLayout = new javax.swing.GroupLayout(leave);
        leave.setLayout(leaveLayout);
        leaveLayout.setHorizontalGroup(
            leaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leaveLayout.createSequentialGroup()
                .addComponent(lsidepane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jDesktopPane2)
                .addContainerGap())
        );
        leaveLayout.setVerticalGroup(
            leaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lsidepane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(leaveLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane2)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Handle leaves", leave);

        addatt.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        addatt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_Checked_User_Male_26px.png"))); // NOI18N
        addatt.setText("Add entry");
        addatt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addattActionPerformed(evt);
            }
        });

        viewa.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        viewa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_Today_26px.png"))); // NOI18N
        viewa.setText("View attendance");
        viewa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewaActionPerformed(evt);
            }
        });

        reportl1.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        reportl1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_Combo_Chart_26px.png"))); // NOI18N
        reportl1.setText("Reports");

        javax.swing.GroupLayout asidepaneLayout = new javax.swing.GroupLayout(asidepane);
        asidepane.setLayout(asidepaneLayout);
        asidepaneLayout.setHorizontalGroup(
            asidepaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(viewa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(reportl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(addatt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        asidepaneLayout.setVerticalGroup(
            asidepaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(asidepaneLayout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(addatt, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94)
                .addComponent(viewa, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96)
                .addComponent(reportl1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(151, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDesktopPane3Layout = new javax.swing.GroupLayout(jDesktopPane3);
        jDesktopPane3.setLayout(jDesktopPane3Layout);
        jDesktopPane3Layout.setHorizontalGroup(
            jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1339, Short.MAX_VALUE)
        );
        jDesktopPane3Layout.setVerticalGroup(
            jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout attendanceLayout = new javax.swing.GroupLayout(attendance);
        attendance.setLayout(attendanceLayout);
        attendanceLayout.setHorizontalGroup(
            attendanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(attendanceLayout.createSequentialGroup()
                .addComponent(asidepane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jDesktopPane3)
                .addContainerGap())
        );
        attendanceLayout.setVerticalGroup(
            attendanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(asidepane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(attendanceLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane3)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Attendance", attendance);

        addc.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        addc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_Checked_26px.png"))); // NOI18N
        addc.setText("Add case");
        addc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addcActionPerformed(evt);
            }
        });

        viewc.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        viewc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_Eye_26px.png"))); // NOI18N
        viewc.setText("View cases");
        viewc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewcActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dsidepaneLayout = new javax.swing.GroupLayout(dsidepane);
        dsidepane.setLayout(dsidepaneLayout);
        dsidepaneLayout.setHorizontalGroup(
            dsidepaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(addc, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(viewc, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        dsidepaneLayout.setVerticalGroup(
            dsidepaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dsidepaneLayout.createSequentialGroup()
                .addContainerGap(227, Short.MAX_VALUE)
                .addComponent(addc, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addComponent(viewc, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(198, 198, 198))
        );

        javax.swing.GroupLayout jDesktopPane4Layout = new javax.swing.GroupLayout(jDesktopPane4);
        jDesktopPane4.setLayout(jDesktopPane4Layout);
        jDesktopPane4Layout.setHorizontalGroup(
            jDesktopPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1339, Short.MAX_VALUE)
        );
        jDesktopPane4Layout.setVerticalGroup(
            jDesktopPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout disciplineLayout = new javax.swing.GroupLayout(discipline);
        discipline.setLayout(disciplineLayout);
        disciplineLayout.setHorizontalGroup(
            disciplineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(disciplineLayout.createSequentialGroup()
                .addComponent(dsidepane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jDesktopPane4)
                .addContainerGap())
        );
        disciplineLayout.setVerticalGroup(
            disciplineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dsidepane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, disciplineLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane4)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Disciplinary", discipline);

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setText("Human Resource Management ");

        jButton1.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jButton1.setText("Logout");

        javax.swing.GroupLayout parentLayout = new javax.swing.GroupLayout(parent);
        parent.setLayout(parentLayout);
        parentLayout.setHorizontalGroup(
            parentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, parentLayout.createSequentialGroup()
                .addGap(348, 348, 348)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(201, 201, 201))
        );
        parentLayout.setVerticalGroup(
            parentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, parentLayout.createSequentialGroup()
                .addGroup(parentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(parentLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(18, 18, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, parentLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 656, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(parent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(parent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        AddEmployee ae = new AddEmployee();
        jDesktopPane1.add(ae).setVisible(true);
    }//GEN-LAST:event_addActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        // TODO add your handling code here:
        EditEmployee ee = new EditEmployee();
        jDesktopPane1.add(ee).setVisible(true);
    }//GEN-LAST:event_editActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        DeleteEmployee de = new DeleteEmployee();
         jDesktopPane1.add(de).setVisible(true);
    }//GEN-LAST:event_deleteActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
        SearchEmployee se = new SearchEmployee();
         jDesktopPane1.add(se).setVisible(true);
    }//GEN-LAST:event_searchActionPerformed

    private void addlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addlActionPerformed
        // TODO add your handling code here:
         AddLeave al = new AddLeave();
         jDesktopPane2.add(al).setVisible(true);
    }//GEN-LAST:event_addlActionPerformed

    private void apigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apigActionPerformed
        // TODO add your handling code here:
        App_Ign_Leave ai = new App_Ign_Leave();
         jDesktopPane2.add(ai).setVisible(true);
    }//GEN-LAST:event_apigActionPerformed

    private void viewlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewlActionPerformed
        // TODO add your handling code here:
        ViewLeave vl = new ViewLeave();
         jDesktopPane2.add(vl).setVisible(true);
    }//GEN-LAST:event_viewlActionPerformed

    private void dellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dellActionPerformed
        // TODO add your handling code here:
        DeleteLeave dl = new DeleteLeave();
         jDesktopPane2.add(dl).setVisible(true);
    }//GEN-LAST:event_dellActionPerformed

    private void searchlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchlActionPerformed
        // TODO add your handling code here:
        SearchLeave sl = new SearchLeave();
         jDesktopPane2.add(sl).setVisible(true);
    }//GEN-LAST:event_searchlActionPerformed

    private void addattActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addattActionPerformed
        // TODO add your handling code here:
        AddEntry ae = new AddEntry();
         jDesktopPane3.add(ae).setVisible(true);
    }//GEN-LAST:event_addattActionPerformed

    private void viewaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewaActionPerformed
        // TODO add your handling code here:
        ViewAttendance va = new ViewAttendance();
         jDesktopPane3.add(va).setVisible(true);
    }//GEN-LAST:event_viewaActionPerformed

    private void addcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addcActionPerformed
        // TODO add your handling code here:
        AddCase ac = new AddCase();
         jDesktopPane4.add(ac).setVisible(true);
    }//GEN-LAST:event_addcActionPerformed

    private void viewcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewcActionPerformed
        // TODO add your handling code here:
        ViewCase vc = new ViewCase();
         jDesktopPane4.add(vc).setVisible(true);
    }//GEN-LAST:event_viewcActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        try{
             UIManager.setLookAndFeel("com.jtattoo.plaf.mcwin.McWinLookAndFeel");
         }
         catch(Exception e){
             e.printStackTrace();
         }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton addatt;
    private javax.swing.JButton addc;
    private javax.swing.JButton addl;
    private javax.swing.JButton apig;
    private javax.swing.JPanel asidepane;
    private javax.swing.JPanel attendance;
    private javax.swing.JButton delete;
    private javax.swing.JButton dell;
    private javax.swing.JPanel discipline;
    private javax.swing.JPanel dsidepane;
    private javax.swing.JButton edit;
    private javax.swing.JPanel emp;
    private javax.swing.JPanel esidepane;
    private javax.swing.JButton jButton1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JDesktopPane jDesktopPane3;
    private javax.swing.JDesktopPane jDesktopPane4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel leave;
    private javax.swing.JPanel lsidepane;
    private javax.swing.JPanel parent;
    private javax.swing.JButton reportl;
    private javax.swing.JButton reportl1;
    private javax.swing.JButton reports;
    private javax.swing.JButton search;
    private javax.swing.JButton searchl;
    private javax.swing.JButton viewa;
    private javax.swing.JButton viewc;
    private javax.swing.JButton viewl;
    // End of variables declaration//GEN-END:variables
}
